#!/usr/bin/env python
import sys
import time
import argparse

PYTHON_VERSION = sys.version_info[0]

parser = argparse.ArgumentParser(description='A tiny tool that takes stdin (or file), and output to stdout line by line with delay.')
parser.add_argument('infile', nargs='?', type=argparse.FileType('r'), default=sys.stdin)
parser.add_argument('-d', type=float, default=1, dest='delay', help='Print by bytes instead of lines')
parser.add_argument('-b', '-c', '--per-byte', '--per-char',
                    type=int, default=0,
                    dest='per_byte',
                    metavar='bytes',
                    help='Print by bytes instead of lines')

args = parser.parse_args()

try:
    while True:
        if PYTHON_VERSION == 3:
            if args.per_byte != 0:
                s = args.infile.buffer.raw.read(args.per_byte)
            else:
                s = args.infile.buffer.raw.readline()

            if len(s) == 0:
                break
            sys.stdout.buffer.raw.write(s)
            sys.stdout.flush()

        else:
            if args.per_byte != 0:
                s = args.infile.read(args.per_byte)
            else:
                s = args.infile.readline()

            if len(s) == 0:
                break
            sys.stdout.write(s)
            sys.stdout.flush()

        time.sleep(args.delay)

except EOFError:
    pass

except KeyboardInterrupt:
    pass
