#!/usr/bin/env python
import sys
import time

PYTHON_VERSION = sys.version_info[0]

per_byte = 0
delay = 1

args = sys.argv[1:]

while len(args) > 0:
    ''' shell-script-style argument parse
    '''
    arg = args[0]
    if arg in ('-b', '-c', '--per-char', '--per-byte'):
        args = args[1:]
        arg = args[0]
        per_byte = int(arg)

    else:
        delay = float(arg)

    args = args[1:]

try:
    while True:
        if PYTHON_VERSION == 3:
            if per_byte != 0:
                s = sys.stdin.buffer.raw.read(per_byte)
            else:
                s = sys.stdin.buffer.raw.readline()

            if len(s) == 0:
                break
            sys.stdout.buffer.raw.write(s)
            sys.stdout.flush()

        else:
            if per_byte != 0:
                s = sys.stdin.read(per_byte)
            else:
                s = sys.stdin.readline()

            if len(s) == 0:
                break
            sys.stdout.write(s)
            sys.stdout.flush()

        time.sleep(delay)

except EOFError:
    pass

except KeyboardInterrupt:
    pass
