#!/usr/bin/env python
import sys
import time

PYTHON_VERSION = sys.version_info[0]

per_byte = False
delay = 1

for arg in sys.argv[1:]:
    if arg in ('-b', '-c', '--per-char', '--per-byte'):
        per_byte = True
    else:
        delay = float(arg)

try:
    while True:
        if PYTHON_VERSION == 3:
            if per_byte:
                s = sys.stdin.buffer.raw.read(1)
            else:
                s = sys.stdin.buffer.raw.readline()

            if len(s) == 0:
                break
            sys.stdout.buffer.raw.write(s)
            sys.stdout.flush()

        else:
            if per_byte:
                s = sys.stdin.read(1)
            else:
                s = sys.stdin.readline()

            if len(s) == 0:
                break
            sys.stdout.write(s)
            sys.stdout.flush()

        time.sleep(delay)

except EOFError:
    pass

except KeyboardInterrupt:
    pass
